Build:
  # Request Amazon Linux 2023 and force upgrade of all of the packages
  ParentImage: arn:aws:imagebuilder:us-east-1:aws:image/amazon-linux-2023-x86/x.x.x
  UpdateOsPackages:
    Enabled: true

  # Customize the AMI components
  Components:
    - Type: script
      Value: s3://sboinfrastructureassets/scripts/ami/install_packages.sh
    # - Type: arn
    #   Value: arn:aws:imagebuilder:us-east-1:671250183987:component/packages/1.0.0/1
    # - Type: arn
    #   Value: arn:aws:imagebuilder:us-east-1:671250183987:component/singularity-ce/1.0.2/1

  # Set the tags for the build process
  Tags:
    - Key: SBO_Billing
      Value: hpc:parallelcluster
  
  # Provide configuration to build the image
  InstanceType: m5.large
  SubnetId: subnet-076ece71c00742d3c # compute
  SecurityGroupIds:
    - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc

Image:
  # Set the tags specifically for the AMI
  Tags:
    - Key: SBO_Billing
      Value: hpc:parallelcluster
