Build:
  # Request Amazon Linux 2023 and force upgrade of all of the packages
  ParentImage: arn:aws:imagebuilder:us-east-1:aws:image/amazon-linux-2023-x86/x.x.x
  UpdateOsPackages:
    Enabled: true

  # Customize the AMI with different components (e.g., AWS CLI, Singularity CE, ..., etc.)
  Components:
    - Type: arn
      Value: arn:aws:imagebuilder:us-east-1:671250183987:component/packages/1.0.0/1
    - Type: arn  # See 'AdditionalIamPolicies' policy below
      Value: arn:aws:imagebuilder:us-east-1:671250183987:component/singularity-ce/4.2.0/1

  Iam:
    # Allow access to the RPMs repository on S3 (e.g., for Singularity CE component)
    AdditionalIamPolicies:
      - Policy: arn:aws:iam::671250183987:policy/SBOInfrastructureAssets_S3GetObject_RPMs

  # Set the tags for the build process (e.g., EC2 instances, Image Builder Components, etc.)
  Tags:
    - Key: SBO_Billing
      Value: hpc:parallelcluster
  
  # Provide configuration to build the image
  InstanceType: m5.large
  SubnetId: subnet-076ece71c00742d3c # compute
  SecurityGroupIds:
    - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc

Image:
  # Set the tags specifically for the AMI
  Tags:
    - Key: SBO_Billing
      Value: hpc:parallelcluster
