name: packages
description: Install RPM Packages
schemaVersion: 1.0
phases:
  - name: build
    steps:
     - name: InstallPackages
       action: ExecuteBash
       inputs:
         commands:
           - |
            # Install the tools that we will need in the ParallelCluster
            dnf search htop && dnf install -y htop
            pip install ClusterShell

            # Install the latest AWS CLI version
            dnf remove -y awscli
            wget -O "/tmp/awscliv2.zip" "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
            unzip /tmp/awscliv2.zip -d /tmp/awscliv2
            /tmp/awscliv2/aws/install
            rm -rf /tmp/awscliv2*
  - name: test
    steps:
      - name: TestPackages
        action: ExecuteBash
        inputs:
          commands:
            - |
             which htop && htop --version | head -n1 && \
             which nodeset && nodeset --version && \
             /usr/local/bin/aws --version
