name: singularity-ce
description: Install Singularity CE
schemaVersion: 1.0
parameters:
  - SingularityVersion:
      type: string
      default: "4.1.5"
      description: The version of singularity to install
phases:
  - name: build
    steps:
     - name: InstallSingularity
       action: ExecuteBash
       inputs:
         commands:
           - |
             set -e
             PACKAGE="singularity-ce-{{ SingularityVersion }}.tar.gz"
             VERSION="v{{ SingularityVersion }}"
             wget --no-verbose "https://github.com/sylabs/singularity/releases/download/${VERSION}/${PACKAGE}"
             dnf install -y rpm-build autoconf automake fuse3-devel glib2-devel golang libseccomp-devel libtool squashfs-tools zlib-devel
             rpmbuild -tb --clean --nodebuginfo singularity-ce-{{ SingularityVersion }}.tar.gz
             dnf install -y /rpmbuild/RPMS/x86_64/singularity-ce-{{ SingularityVersion }}-1.amzn2023.x86_64.rpm
             rm -f ${PACKAGE} /rpmbuild
  - name: test
    steps:
      - name: TestSingularity
        action: ExecuteBash
        inputs:
          commands:
            - which singularity && singularity --version
