name: singularity-ce
description: Install Singularity CE
schemaVersion: 1.0
parameters:
  - SingularityVersion:
      type: string
      default: "4.2.0"
      description: The version of Singularity to install
  - CrunVersion:
      type: string
      default: "1.16.1"
      description: The version of Go to install as dependency
phases:
  - name: build
    steps:
     - name: InstallSingularity
       action: ExecuteBash
       inputs:
         commands:
           - |
             set -euo pipefail

             # Install the necessary dependencies for Singularity
             dnf groupinstall -y 'Development Tools'
             dnf install -y autoconf \
                            automake \
                            cryptsetup \
                            fuse \
                            fuse3 \
                            fuse3-devel \
                            gcc \
                            git \
                            glib2-devel \
                            glibc-static \
                            golang \
                            go-md2man \
                            libcap-devel \
                            libseccomp-devel \
                            libtool \
                            make \
                            pkg-config \
                            python \
                            python3 \
                            python3-libmount \
                            squashfs-tools \
                            systemd-devel \
                            yajl-devel \
                            zlib-devel

             # Setup a temporary directory
             tmpdir=$(mktemp -d) && cd ${tmpdir}

             # Install crun dependency from source
             cd ${tmpdir}
             git clone --recurse-submodules https://github.com/containers/crun.git --branch {{ CrunVersion }}
             cd crun
             ./autogen.sh
             ./configure
             make
             make install

             # Install Singularity from source
             cd ${tmpdir}
             git clone --recurse-submodules https://github.com/sylabs/singularity.git --branch v{{ SingularityVersion }}
             cd singularity
             ./mconfig
             make -C builddir
             make -C builddir install

             # Delete the temporary directory
             rm -rf ${tmpdir}

  - name: test
    steps:
      - name: TestSingularity
        action: ExecuteBash
        inputs:
          commands:
            - which singularity && singularity --version
