Region: us-east-1
Image:
  Os: alinux2
  CustomAmi: ami-081360f17c6e0bb4d
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-076ece71c00742d3c # compute
    SecurityGroups:
    - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
  Ssh:
    KeyName: aws_coreservices
  Iam:
    S3Access:
      - BucketName: sboinfrastructureassets
        EnableWriteAccess: True
  CustomActions:
    OnNodeConfigured:
      Sequence:
        - Script: s3://sboinfrastructureassets/scripts/install_packages.sh
        - Script: s3://sboinfrastructureassets/scripts/create_users.py
          Args:
            - /sbo/home/resources/users.json
        - Script: s3://sboinfrastructureassets/scripts/all_or_nothing_allocation.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_lustre_directories.py
          Args:
            - /sbo/home/resources/users.json
            - /sbo/data
        - Script: s3://sboinfrastructureassets/scripts/setup_slurm.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_environment.sh
          Args:
            - /sbo/data
        - Script: s3://sboinfrastructureassets/scripts/setup_sshd.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_nexus_storage_service.sh
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: debug # for testing purposes
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: t3micro
      Instances:
      - InstanceType: t3.micro
      MinCount: 0
      MaxCount: 8
    Networking:
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
    CustomSlurmSettings:
      MaxNodes: 8
      MaxTime: 1-00:00:00
  - Name: prod-mpi # for tightly coupled jobs
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: cpu-c5n
      Instances:
      - InstanceType: c5n.18xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-c6in
      Instances:
      - InstanceType: c6in.32xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-c7a
      Instances:
      - InstanceType: c7a.48xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # least number of nodes needed to simulate the full O1 circuit
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-m7a
      Instances:
      - InstanceType: m7a.48xlarge # general purpose nodes with large memory capacity
      MinCount: 0
      MaxCount: 4 # number of nodes needed to simulate the full O1 circuit
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-m5n
      Instances:
      - InstanceType: m5n.24xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: nvme
      Instances:
      - InstanceType: c5d.24xlarge # provides additionally nvme support
      MinCount: 0
      MaxCount: 2 # upper limit for functionalizer use-case defined in cost estimation sheet
      Efa:
        Enabled: false
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: true
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
      - sg-0184e34d690eddb22 # sbo-poc-compute / hpc_efa
    CustomSlurmSettings:
      MaxNodes: 6
      MaxTime: 720
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
  - Name: prod-batch # for benchmarking
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: cpu
      Instances:
      - InstanceType: m5.8xlarge # general purpose nodes
      MinCount: 0
      MaxCount: 16 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: false # enable after security groups have been updated
                       # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: false
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    CustomSlurmSettings:
      MaxNodes: 4
      MaxTime: 120
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
  - Name: special-bench # for benchmarking
    AllocationStrategy: lowest-price
    ComputeResources:
      #- Name: m7g.16xlarge
      #  Instances:
      #  - InstanceType: m7g.16xlarge
      #  MinCount: 0
      #  MaxCount: 1
    - Name: c7a-48xlarge
      Instances:
      - InstanceType: c7a.48xlarge
      MinCount: 0
      MaxCount: 1
    - Name: m7a-48xlarge
      Instances:
      - InstanceType: m7a.48xlarge
      MinCount: 0
      MaxCount: 1
    - Name: m6i-32xlarge
      Instances:
      - InstanceType: m6i.32xlarge
      MinCount: 0
      MaxCount: 1
    - Name: m5-24xlarge
      Instances:
      - InstanceType: m5.24xlarge
      MinCount: 0
      MaxCount: 1
    - Name: m4-16xlarge
      Instances:
      - InstanceType: m4.16xlarge
      MinCount: 0
      MaxCount: 1
        #- Name: c7g.16xlarge
        #  Instances:
        #  - InstanceType: c7g.16xlarge
        #  MinCount: 0
        #  MaxCount: 1
    - Name: c6i-32xlarge
      Instances:
      - InstanceType: c6i.32xlarge
      MinCount: 0
      MaxCount: 1
    - Name: c6a-48xlarge
      Instances:
      - InstanceType: c6a.48xlarge
      MinCount: 0
      MaxCount: 1
    - Name: c5-24xlarge
      Instances:
      - InstanceType: c5.24xlarge
      MinCount: 0
      MaxCount: 1
    - Name: c4-8xlarge
      Instances:
      - InstanceType: c4.8xlarge
      MinCount: 0
      MaxCount: 1
        #- Name: hpc7g.16xlarge
        #  Instances:
        #  - InstanceType: hpc7g.16xlarge
        #  MinCount: 0
        #  MaxCount: 1
        #- Name: hpc7a.96xlarge (unavailable in us-east-1)
        #  Instances:
        #  - InstanceType: hpc7a.96xlarge
        #  MinCount: 0
        #  MaxCount: 1
        #- Name: hpc6id.32xlarge
        #  Instances:
        #  - InstanceType: hpc6id.32xlarge
        #  MinCount: 0
        #  MaxCount: 1
        #- Name: hpc6a.48xlarge
        #  Instances:
        #  - InstanceType: hpc6a.48xlarge
        #  MinCount: 0
        #  MaxCount: 1
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: false
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    CustomSlurmSettings:
      MaxNodes: 1
      MaxTime: 60
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    CustomSlurmSettingsIncludeFile: s3://sboinfrastructureassets/config/slurm_extras.conf
Imds:
  ImdsSupport: v2.0
SharedStorage:
  - Name: Efs-Home
    StorageType: Efs
    MountDir: /sbo/home
    EfsSettings:
      FileSystemId: fs-0c2a2f3ad1b1beeca
  - Name: FsxLustre-Scratch
    StorageType: FsxLustre
    MountDir: /sbo/data
    FsxLustreSettings:
      DeploymentType: SCRATCH_2
      StorageCapacity: 1200  # Setup Lustre for 1.2TiB (minimum allowed)
      DataCompressionType: LZ4  # Data compression for higher-throughput between OSSs <-> OSTs
