Region: us-east-1
Image:
  Os: alinux2
  CustomAmi: ami-036a6565c4274982e
HeadNode:
  InstanceType: t3.micro
  Networking:
    SubnetId: subnet-076ece71c00742d3c # compute
    SecurityGroups:
    - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
  Ssh:
    KeyName: aws_coreservices
  Iam:
    S3Access:
      - BucketName: sboinfrastructureassets
        EnableWriteAccess: True
  CustomActions:
    OnNodeConfigured:
      Sequence:
        - Script: s3://sboinfrastructureassets/scripts/create_users.py
          Args:
            - /sbo/home/resources/users.json
        - Script: s3://sboinfrastructureassets/scripts/all_or_nothing_allocation.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_lustre_directories.py
          Args:
            - /sbo/home/resources/users.json
            - /sbo/data
        - Script: s3://sboinfrastructureassets/scripts/setup_slurm.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_environment.sh
          Args:
            - /sbo/data
        - Script: s3://sboinfrastructureassets/scripts/setup_sshd.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_nexus_storage_service.sh
Scheduling:
  Scheduler: slurm
  SlurmQueues:
  - Name: debug # for testing purposes
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: t3micro
      Instances:
      - InstanceType: t3.micro
      MinCount: 0
      MaxCount: 8
    Networking:
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
  - Name: prod-mpi # for tightly coupled jobs
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: cpu-c5n
      Instances:
      - InstanceType: c5n.18xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-c6in
      Instances:
      - InstanceType: c6in.32xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-m5n
      Instances:
      - InstanceType: m5n.24xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: nvme
      Instances:
      - InstanceType: c5d.24xlarge # provides additionally nvme support
      MinCount: 0
      MaxCount: 2 # upper limit for functionalizer use-case defined in cost estimation sheet
      Efa:
        Enabled: false
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: true
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
      - sg-0184e34d690eddb22 # sbo-poc-compute / hpc_efa
    CustomSlurmSettings:
      MaxNodes: 4
      MaxTime: 120
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
  - Name: prod-batch # for benchmarking
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: cpu
      Instances:
      - InstanceType: m5.8xlarge # general purpose nodes
      MinCount: 0
      MaxCount: 16 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: false # enable after security groups have been updated
                       # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: false
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    CustomSlurmSettings:
      MaxNodes: 4
      MaxTime: 120
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Sequence:
          - Script: s3://sboinfrastructureassets/scripts/create_users.py
            Args:
              - /sbo/home/resources/users.json
          - Script: s3://sboinfrastructureassets/scripts/setup_environment_compute.sh
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    CustomSlurmSettingsIncludeFile: s3://sboinfrastructureassets/config/slurm_extras.conf
Imds:
  ImdsSupport: v2.0
SharedStorage:
  - Name: Efs-Home
    StorageType: Efs
    MountDir: /sbo/home
    EfsSettings:
      FileSystemId: fs-0c2a2f3ad1b1beeca
  - Name: FsxLustre-Scratch
    StorageType: FsxLustre
    MountDir: /sbo/data
    FsxLustreSettings:
      DeploymentType: SCRATCH_2
      StorageCapacity: 1200  # Setup Lustre for 1.2TiB (minimum allowed)
      DataCompressionType: LZ4  # Data compression for higher-throughput between OSSs <-> OSTs
