Region: us-east-1
Image:
  Os: alinux2
  CustomAmi: ami-08e31a824b0e1ec59  # alinux2-x86-sbo-pcluster-v5
Tags:
  - Key: SBO_Billing
    Value: parallelcluster
Monitoring:
  Logs:
    CloudWatch:
      RetentionInDays: 90
      DeletionPolicy: Retain
HeadNode:
  InstanceType: t3.medium
  Networking:
    SubnetId: subnet-076ece71c00742d3c # compute
    SecurityGroups:
    - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
  Ssh:
    KeyName: aws_coreservices
  Iam:
    S3Access:
      - BucketName: sboinfrastructureassets
  CustomActions:
    OnNodeConfigured:
      Sequence:
        - Script: s3://sboinfrastructureassets/scripts/setup_users.py
          Args:
            - /sbo/home/resources/users.json
            - /sbo/data
        - Script: s3://sboinfrastructureassets/scripts/setup_slurm.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_sshd.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_slurmrestd_service.sh
        - Script: s3://sboinfrastructureassets/scripts/setup_nexus_storage_service.sh
Scheduling:
  Scheduler: slurm
  ScalingStrategy: all-or-nothing
  SlurmSettings:
    EnableMemoryBasedScheduling: true
    CustomSlurmSettingsIncludeFile: s3://sboinfrastructureassets/config/slurm_extras.conf
    Database:
      Uri: hpc-slurm-db.ctydazornca3.us-east-1.rds.amazonaws.com:3306
      UserName: slurm_admin
      PasswordSecretArn: arn:aws:secretsmanager:us-east-1:671250183987:secret:hpc_slurm_db_password-6LNuBy
  SlurmQueues:
  - Name: debug # for testing purposes
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: t3micro
      Instances:
      - InstanceType: t3.micro
      MinCount: 0
      MaxCount: 8
    Networking:
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Script: s3://sboinfrastructureassets/scripts/setup_users.py
        Args:
          - /sbo/home/resources/users.json
    CustomSlurmSettings:
      MaxNodes: 8
      MaxTime: 1-00:00:00
  - Name: prod-mpi # for tightly coupled jobs
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: cpu-c7a
      Instances:
      - InstanceType: c7a.48xlarge # compute optimized nodes
      MinCount: 0
      MaxCount: 20 # least number of nodes needed to simulate the full O1 circuit x2
      Efa: # low-latency, high BW network
        Enabled: true # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: nvme
      Instances:
      - InstanceType: c5d.24xlarge # provides additionally nvme support
      MinCount: 0
      MaxCount: 2 # upper limit for functionalizer use-case defined in cost estimation sheet
      Efa:
        Enabled: false
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: true
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
      - sg-0184e34d690eddb22 # sbo-poc-compute / hpc_efa
    CustomSlurmSettings:
      MaxNodes: 20
      MaxTime: 720
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Script: s3://sboinfrastructureassets/scripts/setup_users.py
        Args:
          - /sbo/home/resources/users.json
  - Name: prod-batch # for benchmarking
    AllocationStrategy: lowest-price
    ComputeResources:
    - Name: cpu
      Instances:
      - InstanceType: m5.8xlarge # general purpose nodes
      MinCount: 0
      MaxCount: 16 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: false # enable after security groups have been updated
                       # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    - Name: cpu-c7a
      Instances:
      - InstanceType: c7a.48xlarge # general purpose nodes
      MinCount: 0
      MaxCount: 10 # upper limit for largest PoC case defined in cost estimation sheet
      Efa: # low-latency, high BW network
        Enabled: false # enable after security groups have been updated
                       # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security
    Networking:
      PlacementGroup: # try to place nodes close to each other
        Enabled: false
      SubnetIds:
      - subnet-076ece71c00742d3c # compute
      SecurityGroups:
      - sg-0b5941ba4f4d1a9ff # sbo-poc-compute / hpc
    CustomSlurmSettings:
      MaxNodes: 4
      MaxTime: 120
    Iam:
      S3Access:
        - BucketName: sboinfrastructureassets
    CustomActions:
      OnNodeConfigured:
        Script: s3://sboinfrastructureassets/scripts/setup_users.py
        Args:
          - /sbo/home/resources/users.json
Imds:
  ImdsSupport: v2.0
SharedStorage:
  - Name: Efs-Home
    StorageType: Efs
    MountDir: /sbo/home
    EfsSettings:
      FileSystemId: fs-0c2a2f3ad1b1beeca
  - Name: FsxLustre-Persistent
    StorageType: FsxLustre
    MountDir: /sbo/data
    FsxLustreSettings:
      DeploymentType: PERSISTENT_2
      StorageCapacity: 1200  # Setup Lustre FSx for 1.2TiB (minimum allowed)
      PerUnitStorageThroughput: 250  # Request a bandwidth of 250Mbps/TiB (similar to SCRATCH_2)
      DataCompressionType: LZ4  # Data compression for higher-throughput between OSSs <-> OSTs
      DataRepositoryAssociations:
        - Name: Nexus-DRA
          BatchImportMetaDataOnCreate: true
          DataRepositoryPath: s3://sbonexusdata
          FileSystemPath: /project
          AutoExportPolicy: [ NEW, CHANGED, DELETED ]
          AutoImportPolicy: [ NEW, CHANGED, DELETED ]
        - Name: Containers-DRA
          BatchImportMetaDataOnCreate: true
          DataRepositoryPath: s3://sboinfrastructureassets/containers
          FileSystemPath: /containers
          AutoExportPolicy: [ NEW, CHANGED, DELETED ]
          AutoImportPolicy: [ NEW, CHANGED, DELETED ]
