name: compute-efs
description: Mount our shared compute_efs filesystem
schemaVersion: 1.0
phases:
  - name: build
    steps:
     - name: MountEfs
       action: ExecuteBash
       inputs:
         commands:
           - |
             set -xe
             sudo mkdir /compute-efs
             sudo echo "fs-0c2a2f3ad1b1beeca:/ /compute-efs efs _netdev,noresvport,tls,iam 0 0" >> /etc/fstab
             sudo mount -fav
  - name: test
    steps:
      - name: TestEfs
        action: ExecuteBash
        inputs:
          commands:
            - |
              set -xe
              test -d /compute-efs/home
              ls /compute-efs/home

