name: rpm-installer
description: Install RPM Packages
schemaVersion: 1.0
parameters:
  - Packages:
      type: string
      default: "tmux vim htop clustershell"
      description: AL2 packages to install
phases:
  - name: build
    steps:
     - name: InstallPackages
       action: ExecuteBash
       inputs:
         commands:
           - yum install -y {{ Packages }}

